### PR TITLE
Add information disclosure detail page, and fix others.

### LINKED ISSUE #53: Add information disclosure detail page
* Add information disclosure detail page.
* Display the user image that discloses information.
* Users who disclose information divide themselves between regular and emergency.
* Change the page title for each link.

### PR DESCRIPTION
**Pull request by tsukahara-t**
* Add information disclosure detail page.
* Change the page title for each link.

* Change page title on my health and monitoring.
* Replace scroll button text and profile items with i18n format.
* Change top text on slide menu.
* Fix icon style on information disclosure history page.

closes #53

### CODE REVIEW

File: src/html/js/user.js [hunk 1]
```diff
@@ -765,8 +765,8 @@ function closeHelpConfirm(f) {
 }
 
 function viewInfoDisclosureDetail(type){
-    // dummy function
-    console.log(type);
+    $("#viewInfoDisclosureDetail #pageTitle").html(i18next.t("profile." + type));
```
Comment (dixonsiu) [inline src/html/js/user.js]: If you want the element to be translated dynamically, it is better to do the following.  

         $('#viewInfoDisclosureDetail #pageTitle')
              .attr('data-i18n', 'profile.'+ type)
              .localize();

Comment (dixonsiu) [inline src/html/js/user.js]: Any reason why you cannot use $('#pageTitle') which is supposed to be unique, too?

**Review by dixonsiu — CHANGES_REQUESTED** [review]

**Review by atsX — APPROVED** [review]
